name: Verifying

on: [push]
jobs:

  tests:
    name: Compile & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Unit-Test
        run: mvn clean test -f labs/pom.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Report
          path: labs/target/surefire-reports/*.xml
          reporter: java-junit
